### ISSUE TITLE
black IAS indicator

### ISSUE THREAD

**Issue by vezza** [BAWV12/Concorde#2]
The IAS indicator is black...
![IAS indicator](https://user-images.githubusercontent.com/1450066/63656332-af32b780-c792-11e9-8286-ed22f18daa9f.png)

**Comment by BAWV12** [comment]
This is not Concorde problem, but FlightGear's module OpenSceneGraph used in FG2019.2.0 and its function OSGTEXT. If You will use download and compile script and build Your own FlightGear version 2019.1.2, gauges will be OK. Or You can use older 2018.3.1 version.
More info at https://forum.flightgear.org/viewtopic.php?p=352335#p352335

Case closed.
